# NOTE: https://github.com/pydio/cells/issues/19#issuecomment-438741945

version: '3'

services:
  pydio:
    image: pydio/cells:1.4.1
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/root/.config/pydio/cells
    environment:
      - CELLS_BIND=0.0.0.0:8080
      - CELLS_EXTERNAL=${DOMAIN:?err}
      - CELLS_NO_SSL=1
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal
      - traefik

  mysql:
    image: mysql:5.7
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: myp@ssw0rd
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: myp@ssw0rd
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 150M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
